/*
 *
 * Task code generated by SAS Studio 3.7 
 *
 * Generated on '10/7/18, 10:10 PM' 
 * Generated by 'jonduan0' 
 * Generated on server 'ODAWS03.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-693.21.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M5P09132017' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 OPR/55.0.2994.61' 
 * Generated on web client 'https://odamid.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-07%253A00&https%3A%2F%2Fodamid.oda.sas.com%2FSASStudio%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc means data=SASHELP.CARS chartype mean std min max n vardef=df;
	var Weight;
run;

proc univariate data=SASHELP.CARS vardef=df noprint;
	var Weight;
	histogram Weight / normal(noprint);
run;







/*--Scatter Plot Matrix--*/

title 'Vehicle Profile';
proc sgscatter data=sashelp.cars(where=(type in ('Sedan' 'Sports')));
  label mpg_city='City';
  label mpg_highway='Highway';
  matrix mpg_city mpg_highway horsepower weight /
     transparency=0.8 markerattrs=graphdata3(symbol=circlefilled);
  run;



  /*--Scatter Plot Matrix--*/

title 'Vehicle Profile';
proc sgscatter data=sashelp.cars(where=(type in ('Sedan' 'Sports')));
  label mpg_city='City';
  label mpg_highway='Highway';
  matrix mpg_city mpg_highway horsepower weight /
     transparency=0.8 markerattrs=graphdata3(symbol=circlefilled);
  run;
